### ISSUE TITLE
Talkie premium wont read from cliboard no longer

### ISSUE THREAD

**Issue by jeremymeijer** [joelpurra/talkie#15]
Hey,

I've been using talkie for reading purposes since I'm partly blind. Really helpfull, but recently the chrome plugin stopped support for reading clipboard texts. The hotkeys wont work, neither does the context-menu item "read from clipboard".

That's all actually.
a
Kind regards,

Jeremy

### System information

- Your browser: Google chrome
- Your browser version: 86.0.4240.75 (Official build) (64-bits)
- Your operating system: Windows 10 Pro
- Your operating system version: 10.0.19041 Build 19041

**Comment by joelpurra** [comment]
@jeremymeijer: I can confirm the issue. I can also confirm that it can be fixed; it is related to a workaround for the clipboard browser permissions check for older versions of Firefox. A new release of Talkie Premium is coming in the next days. Thank you for reporting! =)

**Comment by joelpurra** [comment]
Talkie Premium v5.0.3 has been released to Github and the Chrome Web Store (CWS). The free Talkie will follow, both in CWS and Firefox Add-ons (AMO) although it shouldn't make a difference there.

- The problem was, as hinted at, the missing (since Chrome had it already) Firefox feature [Permissions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions), which was actually implemented quite some time ago.
- This subsequently lead to a breaking change in the [`webextension-polyfill`](https://github.com/mozilla/webextension-polyfill) support library, which Talkie uses since even longer ago, as it prioritizes wrapping Firefox API support and thus ignores Google Chrome-only functionality.
- Once Talkie (in v5.0.2) upgraded to a version of `webextension-polyfill` which supports (only) the Permissions API as implemented in Firefox, it (surprisingly) affected Talkie Premium on Google Chrome.
- This happened due to failing some basic Permissions API call assertions by passing a callback (based on the original Google Chrome implementation) instead of using the (now) promisified result (as implemented by Firefox and thus `webextension-polyfill`).
- The problem wasn't noticed earlier, when Talkie v5.0.2 was created, because Google Chrome delayed the deployment of Talkie Premium v5.0.2 for months.
- The fix is to use the promisified version of the Permissions API also in Google Chrome, as wrapped by `webextension-polyfill`.
- The issue is a reminder that automated testing is missing, and that it needs to be done cross-browser and cross-variant of Talkie.

@jeremymeijer: I didn't work on v5.0.3 on my main developer machine, and couldn't test in all regular browsers/operating systems. Could you verify that things work as expected, once you get v5.0.3?

**Comment by jeremymeijer** [comment]
Great! Works like a charm again.. 
👍

**Comment by joelpurra** [comment]
@jeremymeijer: happy to hear! Thank you for reporting the issue and verifying the fix =)
