### ISSUE TITLE
working in ubuntu 16.04

### ISSUE THREAD

**Issue by Goddard** [joelpurra/talkie#3]
I am using Vivaldi trying to get this working.  Any reason why this wouldn't work?

**Comment by joelpurra** [comment]
@Goddard: my basic tests just gives me a pretty useless "unknown error" in the developer console output when I try to use Talkie to read a news article. Speaking test text in the Talkie options works well though, which is good news.

Seems there is some difference between the extension API in Google Chrome and Vivaldi, possibly related to getting the selected text from a page. This will require a bit more investigation. Do you have any clue as to what the specific problem might be? Can have a look tomorrow; if there's an API difference I will look for a workaround =)

Also, just to check: do you have any voices installed in Vivaldi? You can check in Talkie's options, but if that doesn't work try installing [US English Female Text-to-speech (by Google)](https://chrome.google.com/webstore/detail/us-english-female-text-to/pkidpnnapnfgjhfhkpmjpbckkbaodldb).

Thanks for the report!

**Comment by joelpurra** [comment]
@Goddard: it seems that Vivaldi doesn't support [`chrome.tabs.detectLanguage`](https://developer.chrome.com/extensions/tabs#method-detectLanguage), at least not on my machine, which is why there was an "unknown error". Fortunately, the page language is the last fallback when it comes to language detection (after detected text language, selected element language, parent elements languages). With this in mind, I do hope that other language and voice features in Vivaldi work as expected.

Can you confirm the fix, please? If there are additional problems, we can reopen the issue.

Another problem I noticed in Vivaldi was that keyboard shortcuts do not seem to work very well. Talkie's shortcuts are listed properly under `chrome://extensions/configureCommands` but do not have any effect. I've found several Vivaldi bug reports regarding shortcuts and extensions in the forums. I assume a fix will be coming at some point, so won't make changes to Talkie.

Thanks again =)

**Comment by joelpurra** [comment]
@Goddard: by the way, [Talkie v2.0.1 is now available](https://chrome.google.com/webstore/detail/talkie/enfbcfmmdpdminapkflljhbfeejjhjjk) in the chrome web store. Please check which version you have installed in `chrome://extensions/` as it should update automatically (at some point).

**Comment by Goddard** [comment]
running 2.0.2 now and it looks like it gets triggered, meaning it will change the icon from the play to the stop icon, but I hear no sound. 

It works on chrome though.

**Comment by joelpurra** [comment]
@Goddard: hmm. Just tested locally, and it works to both right-click text and use the Talkie button in the toolbar.

- Did you check if there are any voices available in Vivaldi?
- Are there voices for the (assumed) language of the text/page?
- [Does Talkie work on Wikipedia?](https://en.wikipedia.org/wiki/Language)
- Which version of Vivaldi? I'm testing using 1.7.735.46 (Stable channel) (64-bit).
- Are there any errors listed when inspecting Talkie's background page console log? [Here's how to find the background console log for an extension.](https://stackoverflow.com/questions/10257301/where-to-read-console-messages-from-background-js-in-a-chrome-extension)
- Could you please copy-paste the log including errors here?

**Comment by joelpurra** [comment]
@Goddard: haven't received any reply so far, so am closing this issue. Reply to reopen. Thanks!

**Comment by Goddard** [comment]
I am on vacation and haven't had a chance to test as of yet.  I will give it a go.  Thanks for the updates.

**Comment by joelpurra** [comment]
@Goddard: no worries =) It would be best for Talkie if any issues could be resolved, but figured I would clean up the issue only due to inactivity. Check again after you vacation if you feel like it =)
